[package]
name = "job_declaration_sv2"
version = "1.0.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "SV2 job declaration protocol types"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"


[dependencies]
serde = { version = "1.0.89", default-features = false, optional = true }
binary_sv2 = { version = "^1.0.0", path = "../../../../protocols/v2/binary-sv2/binary-sv2" }
const_sv2 = { version = "^1.0.0", path = "../../../../protocols/v2/const-sv2" }

[features]
with_serde = ["binary_sv2/with_serde", "serde"]
