[package]
name = "codec_sv2"
version = "1.0.1"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 data format"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"

[dependencies]
serde = { version = "1.0.89", default-features = false, optional = true }
framing_sv2 = {version = "1.0.0", path = "../../../protocols/v2/framing-sv2" }
noise_sv2 = { version = "1.0", path = "../../../protocols/v2/noise-sv2", optional = true }
binary_sv2 = { version = "1.0.0", path = "../../../protocols/v2/binary-sv2/binary-sv2" }
const_sv2 = { version = "1.0.0", path = "../../../protocols/v2/const-sv2" }
buffer_sv2 = { version = "1.0.0", path = "../../../utils/buffer" }
tracing = { version = "0.1" }


[features]
with_serde = [
  "binary_sv2/with_serde",
  "serde",
  "framing_sv2/with_serde",
  "buffer_sv2/with_serde",
]
with_buffer_pool = ["framing_sv2/with_buffer_pool"]
