[package]
name = "binary_codec_sv2"
version = "1.0.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 data format"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickcheck = { version = "1.0.0", optional = true }
buffer_sv2 = { version = "^1.0.0", path = "../../../../../utils/buffer", optional = true }

[features]
no_std = []
default = ["no_std"]
prop_test = ["quickcheck"]
with_buffer_pool = ["buffer_sv2"]
