[package]
name = "pool_sv2"
version = "0.1.0"
edition = "2018"
description = "SV2 pool role"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"

[dependencies]
stratum-common = { path = "../../common" }
async-channel = "1.5.1"
binary_sv2 = { version = "^0.1.6", path = "../../protocols/v2/binary-sv2/binary-sv2" }
buffer_sv2 = { version = "^0.1.2", path = "../../utils/buffer" }
codec_sv2 = { version = "1.0", path = "../../protocols/v2/codec-sv2", features = ["noise_sv2"] }
const_sv2 = { version = "^0.1.2", path = "../../protocols/v2/const-sv2" }
network_helpers = { version = "0.1", path = "../../utils/network-helpers", features =["with_tokio","with_buffer_pool"] }
noise_sv2 = { version = "1.0", path = "../../protocols/v2/noise-sv2" }
rand = "0.8.4"
roles_logic_sv2 = { version = "^0.1.0", path = "../../protocols/v2/roles-logic-sv2" }
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false }
tokio = { version = "1", features = ["full"] }
toml = { version = "*", git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }
tracing = { version = "0.1" }
tracing-subscriber = "0.3"
async-recursion = "1.0.0"
error_handling = { version = "0.1", path = "../../utils/error-handling" }
nohash-hasher = "0.2.0"
key-utils = { version = "^1.0.0", path = "../../utils/key-utils" }
secp256k1 = { version = "0.27.0", default-features = false, features =["bitcoin_hashes","alloc","rand","rand-std"] }


[dev-dependencies]
hex = "0.4.3"

[features]
test_only_allow_unencrypted = []
MG_reject_auth = []

#[lib]
#crate-type = ["cdylib"]
