on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

name: Rustfmt + Taplo

jobs:
  fmt:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run fmt in different workspaces and crates
        run: |
          cargo fmt --all --manifest-path=benches/Cargo.toml -- --check
          cargo fmt --all --manifest-path=common/Cargo.toml -- --check
          cargo fmt --all --manifest-path=protocols/Cargo.toml -- --check
          cargo fmt --all --manifest-path=roles/Cargo.toml -- --check
          cargo fmt --all --manifest-path=utils/Cargo.toml -- --check
          cargo fmt --all --manifest-path=utils/message-generator/Cargo.toml -- --check

      - name: Install Taplo
        run: cargo install taplo-cli

      - name: Run Taplo
        id: taplo-check
        run: taplo fmt --check